### ISSUE TITLE
Specification request Webapp: header App-Chooser

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-design-system#1]
* Please link to the component in question *
Component: header App-Chooser

* What would you like to have specified? Behavior, Animation, Design, ...? *

- [ ] How does the App-Chooser look like?
- [ ] What is the behavior when clicking on the App-Chooser icon?
- [ ] Are there differences for mobile/tablet/desktop?

**Comment by Frenggi** [comment]
Thank you for the request and sorry for the delay. We will describe it in the header pattern.
