### ISSUE TITLE
Specification Request Webapp: Status

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-design-system#12]
Which color/icon variants should be provided by default?
Currently only the green/check variant is defined.

I would recommend having at least the following states specified:
- valid (already available)
- invalid
- warning

**Comment by Frenggi** [comment]
Thank you @kyubisation for the request. The idea was, that the status could be provided project-specific with the twi alternatives (only icon, icon and text). Therefore currently there is no list of status and associated colours defined from the design system.
But we try to identify some basic status which should be available in several projects.

**Comment by kyubisation** [comment]
As mentioned, I believe the most common ones are valid, invalid (e.g. cross, red) and warning (e.g. exclamation mark, yellow).

**Comment by Frenggi** [comment]
The following images show examples for the three proposed status. They will be included in new version of the design system documentation.

![Status_Bubble@3x](https://user-images.githubusercontent.com/6129137/68693202-25b3aa00-0577-11ea-9ea8-66a74b456d2c.png)
![Status_Extended@3x](https://user-images.githubusercontent.com/6129137/68693203-25b3aa00-0577-11ea-9e60-91e2881edd5b.png)

**Comment by Frenggi** [comment]
The documentation on digital.sbb.ch has been adapted with the three standard status and the description that project-specific status with specific icons and colors are allowed.
Therefore I close this issue.
