### ISSUE TITLE
Feature Request Webapp: Responsive sbb-header

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-design-system#17]
**Is your feature request related to a problem? Please describe.**
angular component sbb-header should be responsive

**Describe the solution you'd like**
sbb-header should be responsive. on a mobile view it should be collapsed.

![image](https://user-images.githubusercontent.com/29278232/65029392-f5b4a580-d93d-11e9-99d1-5e21a60a0e8a.png)

**Comment by Frenggi** [comment]
The UX specification has been finished. The implementation of the Angular Component Library is adapted but not already support sub-menus (https://github.com/SchweizerischeBundesbahnen/sbb-angular/releases/tag/8.6.0). Although the part of specification is finished I close this issue.
