### ISSUE TITLE
Feature Request Website: Hover on Tag-Component

### ISSUE THREAD

**Issue by sandrocorradi** [sbb-design-systems/sbb-design-system#19]
**Is your feature request related to a problem? Please describe.**
In Kabenas, weeks ago we hab a Tag-component of Bootstrap in use, which had a hover effect. Since we replaced the component with the Tag-Component of SBB's public design system, we don't have the hover anymore. The hover was similar or the same as the pills of the SBB Intranet. 

**Describe the solution you'd like**
A hover on Tag-Component, comparing to the pills of the SBB Intranet. 

**Describe alternatives you've considered**
We can keep it like this or we can try to make the change just for Kabenas. 

**Additional context**

**Comment by mikemorgenthaler** [comment]
Thank's for your feature request.
We'll check that and keep you informed about the next steps.
