### ISSUE TITLE
Feature Request Website: Typography Title-Value-List

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-design-system#2]
**Is your feature request related to a problem? Please describe.**
Currently there seems to be no specification for a simple title-value list.

**Describe the solution you'd like**
Either a specification for title-value lists or an alternative that should be used.

**Additional context**
Example
![image](https://user-images.githubusercontent.com/594745/61958067-ea3da180-afc0-11e9-8770-074c0feb7fbe.png)

**Comment by Frenggi** [comment]
This already exists as a characteristic of the table pattern: https://digital.sbb.ch/de/websites/components/table
