### ISSUE TITLE
Feature Request Webapp: Month picker

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-design-system#4]
**Is your feature request related to a problem? Please describe.**
We have a specific use cases where our customers want to see reports by month.

Selecting a month with the current datepicker isn't very clear, as the user has to select any day within that month and it will always selects that whole month. (As opposed to the next 30 days).

**Describe the solution you'd like**
Specification for a month picker

**Describe alternatives you've considered**
Currently the datepicker is used.

**Additional context**
Original Requester: @timschoch

Requirements:

- The popup only shows months and years to choose from, but no calendar.
- Option to only show the current and past month
- By clicking the arrows, the month gets advanced
- Label in the Input shows month and year

**Comment by timschoch** [comment]
After some more thought, I'd change the second Requirement to something more broad:
*limit the available options to a specific date range.*

This way we can set the startdate, enddate or both of them.

**Comment by Frenggi** [comment]
Thank you for the request and sorry for the delay. 
As already commented in #5 it seems to be a very specific need for a specific use case. Therefore I'm not sure now if it should be included in the generic design system. But we will discuss it also internally.

**Comment by timschoch** [comment]
Hello @Frenggi, do you have a decision on this?

**Comment by Frenggi** [comment]
Sorry for the long delay on answering this issue.
Same as for week picker (#5): I ask several projects for the same need. Currently there is no need for such a feature of any other project. I suggest you make a proposal for a design solution which we afterwards can consider for generalization in the design system.
Therefore I close the issue for now.
