### ISSUE TITLE
Feature Request Webapp: Week picker

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-design-system#5]
**Is your feature request related to a problem? Please describe.**
We have a specific use cases where our customers can order by calendar week.

With the current datepicker, this isn't very clear, as the user has to select any day within that week and it will always selects that whole week. (As opposed to the next 7 days)

**Describe the solution you'd like**
Specification for a week picker

**Additional context**
Original Requester: @timschoch

Requirements:

- The popup calendar highlights the whole week on hover, clearly showing what time frame will be selected.
- Option to only show the current and future weeks
- By clicking the arrows, the week gets advanced
- Label in the Input shows Calendar Week and first- and last date of that Week (Mo-Su). eg: KW10, 28.3 - 3.4.

**Comment by timschoch** [comment]
After some more thought, I'd change the second Requirement to something more broad:
*limit the available options to a specific date range.*

This way we can set the startdate, enddate or both of them.

**Comment by Frenggi** [comment]
Thank you for the request and sorry for the delay. It seems to be a very specific need for a specific use case. Therefore I'm not sure now if it should be included in the generic design system. But we will discuss it again internally.

**Comment by Frenggi** [comment]
Sorry for the long delay on answering this issue. I ask several projects for the same need. Currently there is no need for such a feature of any other project. I suggest you make a proposal for a design solution which we afterwards can consider for generalization in the design system.
Therefore I close the issue for now.
