### ISSUE TITLE
Feature Request Webapp: Tooltip on hover

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-design-system#6]
**Is your feature request related to a problem? Please describe.**
Currently the tooltip can only be triggered on click - we'd need the tooltip to trigger on hover of an arbitray elements. There should be configurable delays for show/hide.

**Describe the solution you'd like**
Specification whether this should be possible and if there are restrictions or other things to consider.

**Additional context**
https://github.com/SchweizerischeBundesbahnen/sbb-angular/issues/110

**Comment by Frenggi** [comment]
Thank you for the request and sorry for the delay.
We totally agree, that it should be possible, to use the tooltip also by hover. We will adapt the pattern description in near future.

**Comment by Frenggi** [comment]
The rules of the tooltip are adapted to allow it also on hover. Also the component of the Angular component library is already adapted.
